CREATE TABLE inscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inscription_id TEXT UNIQUE,
  created_at TIMESTAMP DEFAULT now(),
  commit_txid TEXT,
  reveal_txid TEXT,
  ordinals_address TEXT
);
