/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BitcoinRouteImport } from './routes/bitcoin'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BitcoinIndexRouteImport } from './routes/bitcoin.index'
import { Route as BitcoinCollectionRouteImport } from './routes/bitcoin.collection'
import { Route as ApiArtTokenIdRouteImport } from './routes/api.art.$tokenId'
import { Route as ApiMetadataTokenIdRouteImport } from './routes/api.metadata.$tokenId'
import { Route as BitcoinApiBroadcastRevealRouteImport } from './routes/bitcoin.api.broadcast-reveal'
import { Route as BitcoinApiPrepareCommitRouteImport } from './routes/bitcoin.api.prepare-commit'
import { Route as BitcoinApiPrepareRevealRouteImport } from './routes/bitcoin.api.prepare-reveal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitcoinRoute = BitcoinRouteImport.update({
  id: '/bitcoin',
  path: '/bitcoin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BitcoinIndexRoute = BitcoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BitcoinRoute,
} as any)
const BitcoinCollectionRoute = BitcoinCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => BitcoinRoute,
} as any)
const ApiArtTokenIdRoute = ApiArtTokenIdRouteImport.update({
  id: '/api/art/$tokenId',
  path: '/api/art/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataTokenIdRoute = ApiMetadataTokenIdRouteImport.update({
  id: '/api/metadata/$tokenId',
  path: '/api/metadata/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const BitcoinApiBroadcastRevealRoute =
  BitcoinApiBroadcastRevealRouteImport.update({
    id: '/api/broadcast-reveal',
    path: '/api/broadcast-reveal',
    getParentRoute: () => BitcoinRoute,
  } as any)
const BitcoinApiPrepareCommitRoute = BitcoinApiPrepareCommitRouteImport.update({
  id: '/api/prepare-commit',
  path: '/api/prepare-commit',
  getParentRoute: () => BitcoinRoute,
} as any)
const BitcoinApiPrepareRevealRoute = BitcoinApiPrepareRevealRouteImport.update({
  id: '/api/prepare-reveal',
  path: '/api/prepare-reveal',
  getParentRoute: () => BitcoinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitcoin': typeof BitcoinRouteWithChildren
  '/collection': typeof CollectionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bitcoin/collection': typeof BitcoinCollectionRoute
  '/bitcoin/': typeof BitcoinIndexRoute
  '/api/art/$tokenId': typeof ApiArtTokenIdRoute
  '/api/metadata/$tokenId': typeof ApiMetadataTokenIdRoute
  '/bitcoin/api/broadcast-reveal': typeof BitcoinApiBroadcastRevealRoute
  '/bitcoin/api/prepare-commit': typeof BitcoinApiPrepareCommitRoute
  '/bitcoin/api/prepare-reveal': typeof BitcoinApiPrepareRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bitcoin/collection': typeof BitcoinCollectionRoute
  '/bitcoin': typeof BitcoinIndexRoute
  '/api/art/$tokenId': typeof ApiArtTokenIdRoute
  '/api/metadata/$tokenId': typeof ApiMetadataTokenIdRoute
  '/bitcoin/api/broadcast-reveal': typeof BitcoinApiBroadcastRevealRoute
  '/bitcoin/api/prepare-commit': typeof BitcoinApiPrepareCommitRoute
  '/bitcoin/api/prepare-reveal': typeof BitcoinApiPrepareRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitcoin': typeof BitcoinRouteWithChildren
  '/collection': typeof CollectionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bitcoin/collection': typeof BitcoinCollectionRoute
  '/bitcoin/': typeof BitcoinIndexRoute
  '/api/art/$tokenId': typeof ApiArtTokenIdRoute
  '/api/metadata/$tokenId': typeof ApiMetadataTokenIdRoute
  '/bitcoin/api/broadcast-reveal': typeof BitcoinApiBroadcastRevealRoute
  '/bitcoin/api/prepare-commit': typeof BitcoinApiPrepareCommitRoute
  '/bitcoin/api/prepare-reveal': typeof BitcoinApiPrepareRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitcoin'
    | '/collection'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bitcoin/collection'
    | '/bitcoin/'
    | '/api/art/$tokenId'
    | '/api/metadata/$tokenId'
    | '/bitcoin/api/broadcast-reveal'
    | '/bitcoin/api/prepare-commit'
    | '/bitcoin/api/prepare-reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bitcoin/collection'
    | '/bitcoin'
    | '/api/art/$tokenId'
    | '/api/metadata/$tokenId'
    | '/bitcoin/api/broadcast-reveal'
    | '/bitcoin/api/prepare-commit'
    | '/bitcoin/api/prepare-reveal'
  id:
    | '__root__'
    | '/'
    | '/bitcoin'
    | '/collection'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bitcoin/collection'
    | '/bitcoin/'
    | '/api/art/$tokenId'
    | '/api/metadata/$tokenId'
    | '/bitcoin/api/broadcast-reveal'
    | '/bitcoin/api/prepare-commit'
    | '/bitcoin/api/prepare-reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitcoinRoute: typeof BitcoinRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiArtTokenIdRoute: typeof ApiArtTokenIdRoute
  ApiMetadataTokenIdRoute: typeof ApiMetadataTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitcoin': {
      id: '/bitcoin'
      path: '/bitcoin'
      fullPath: '/bitcoin'
      preLoaderRoute: typeof BitcoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitcoin/': {
      id: '/bitcoin/'
      path: '/'
      fullPath: '/bitcoin/'
      preLoaderRoute: typeof BitcoinIndexRouteImport
      parentRoute: typeof BitcoinRoute
    }
    '/bitcoin/collection': {
      id: '/bitcoin/collection'
      path: '/collection'
      fullPath: '/bitcoin/collection'
      preLoaderRoute: typeof BitcoinCollectionRouteImport
      parentRoute: typeof BitcoinRoute
    }
    '/api/art/$tokenId': {
      id: '/api/art/$tokenId'
      path: '/api/art/$tokenId'
      fullPath: '/api/art/$tokenId'
      preLoaderRoute: typeof ApiArtTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/$tokenId': {
      id: '/api/metadata/$tokenId'
      path: '/api/metadata/$tokenId'
      fullPath: '/api/metadata/$tokenId'
      preLoaderRoute: typeof ApiMetadataTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitcoin/api/broadcast-reveal': {
      id: '/bitcoin/api/broadcast-reveal'
      path: '/api/broadcast-reveal'
      fullPath: '/bitcoin/api/broadcast-reveal'
      preLoaderRoute: typeof BitcoinApiBroadcastRevealRouteImport
      parentRoute: typeof BitcoinRoute
    }
    '/bitcoin/api/prepare-commit': {
      id: '/bitcoin/api/prepare-commit'
      path: '/api/prepare-commit'
      fullPath: '/bitcoin/api/prepare-commit'
      preLoaderRoute: typeof BitcoinApiPrepareCommitRouteImport
      parentRoute: typeof BitcoinRoute
    }
    '/bitcoin/api/prepare-reveal': {
      id: '/bitcoin/api/prepare-reveal'
      path: '/api/prepare-reveal'
      fullPath: '/bitcoin/api/prepare-reveal'
      preLoaderRoute: typeof BitcoinApiPrepareRevealRouteImport
      parentRoute: typeof BitcoinRoute
    }
  }
}

interface BitcoinRouteChildren {
  BitcoinCollectionRoute: typeof BitcoinCollectionRoute
  BitcoinIndexRoute: typeof BitcoinIndexRoute
  BitcoinApiBroadcastRevealRoute: typeof BitcoinApiBroadcastRevealRoute
  BitcoinApiPrepareCommitRoute: typeof BitcoinApiPrepareCommitRoute
  BitcoinApiPrepareRevealRoute: typeof BitcoinApiPrepareRevealRoute
}

const BitcoinRouteChildren: BitcoinRouteChildren = {
  BitcoinCollectionRoute: BitcoinCollectionRoute,
  BitcoinIndexRoute: BitcoinIndexRoute,
  BitcoinApiBroadcastRevealRoute: BitcoinApiBroadcastRevealRoute,
  BitcoinApiPrepareCommitRoute: BitcoinApiPrepareCommitRoute,
  BitcoinApiPrepareRevealRoute: BitcoinApiPrepareRevealRoute,
}

const BitcoinRouteWithChildren =
  BitcoinRoute._addFileChildren(BitcoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitcoinRoute: BitcoinRouteWithChildren,
  CollectionRoute: CollectionRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiArtTokenIdRoute: ApiArtTokenIdRoute,
  ApiMetadataTokenIdRoute: ApiMetadataTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
